# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://mszdg.easonjan.top//
date_format: "ordinal"
title: MSZ开发者社区
subtitle: "闵行实中 X MSZ开发者社区"
description: "MSZ开发者社区的博客"
keywords: MSZ开发者社区,开发者社区,闵行区实验高级中学,闵行实高,MSZDG,mszdg
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2022
# 源码仓库，请替换成自己的
repository: MSZDevelopmentGroup/MSZ-Developer-Groups
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: weibo,qq,wechat,qzone,twitter,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: MSZ开发者社区
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: MSZ开发者社区
organization: MSZ开发者社区
organization_url: http://mszdg.easonjan.top//
github_username: EasonHelloWord
location: Shanghai, China
email: mszdg@easonjan.top

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /posts/
#     label: 博客

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
disqus_username: easonhelloword.github.io
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: https://easonhelloword.github.io
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: EasonHelloWord
    repo: MSZDG-blog-comments
    oauth:
        client_id: ef8af247f70a7597052e
        client_secret: 6c92ab3067e8fab2ba35ec2090602ee493648e83
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: EasonHelloWord
    repo: MSZDG-blog-comments
    clientID: ef8af247f70a7597052e
    clientSecret: 6c92ab3067e8fab2ba35ec2090602ee493648e83
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: EasonHelloWord/MSZ-Developer-Groups
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: EasonHelloWord/MSZ-Developer-Groups
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: MSZDevelopmentGroup/MSZ-Developer-Groups
    repo-id: R_kgDOKphCSw
    category: Announcements
    category-id: DIC_kwDOKphCS84Casuz
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
